name: stick_box
description: A new Flutter project.

publish_to: "none"

version: 1.2.0+3

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.10

  shared_preferences: ^2.0.15

  share_plus: ^4.0.4

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.2
  provider: ^6.0.3

  firebase_core: ^1.20.0

  firebase_auth:

  google_sign_in:

  connectivity_plus: ^2.3.6

  cloud_firestore: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  package_info_plus: ^1.4.3

flutter_icons:
  android: true
  image_path: "assets/logo/noteslogo2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
